# Classification Project

### Main Objective: Why are our customers churning?

#### Initial questions:
- Could the month in which they signed up influence churn?
- Are there features that indicate a higher propensity to churn?
- Is there a price threshold for specific services where the likelihood of churn increases once price for those services goes past that point? If so, what is that point for what service(s)?
- If we looked at churn rate for month-to-month customers after the 12th month and that of 1-year contract customers after the 12th month, are those rates comparable?

#### Deliverables:
- Report on "Why are customers are churning?"
- A csv with the customer_id, probability of churn and the prediction of churn
- A single google slide that illustrates how your model works, including the features being used, so that I can deliver this to the SLT when they come with questions on how these values were delived.
- How likely is it that the model with have a high probability of churn when churn **doesn't occur**, to give a low probability of chrn when churn occurs, and to accurately predict churn
- A .py file that will take in a new dataset and perform the transformations necessary to run the model you have developed on this new dataset to provide probabilities and predictions

### Acquisition

In [1]:
import pandas as pd

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler

In [2]:
import env

def get_connection(db, user=env.user, host=env.host, password=env.password):
    return f'mysql+pymysql://{user}:{password}@{host}/{db}'

In [3]:
def get_telco_data():
    '''gets all telco data from sql dbase'''
    return pd.read_sql('\
    SELECT c.*, ct.contract_type, ist.internet_service_type, pt.payment_type FROM customers c\
    JOIN contract_types ct ON c.contract_type_id = ct.contract_type_id\
    JOIN internet_service_types ist ON c.internet_service_type_id = ist.internet_service_type_id\
    JOIN payment_types pt ON c.payment_type_id = pt.payment_type_id',\
    get_connection('telco_churn'))

In [4]:
df = get_telco_data()

In [5]:
def peekatdata(df):
    head_df = df.head()
    print(head_df)
    tail_df = df.tail()
    print(tail_df)
    shape_tuple = df.shape
    print(shape_tuple)
    describe_df = df.describe
    print(describe_df)
    print(df.info())

In [6]:
peekatdata(df)

  customer_id  gender  senior_citizen partner dependents  tenure  \
0  0003-MKNFE    Male               0      No         No       9
1  0013-MHZWF  Female               0      No        Yes       9
2  0015-UOCOJ  Female               1      No         No       7
3  0023-HGHWL    Male               1      No         No       1
4  0032-PGELS  Female               0     Yes        Yes       1

  phone_service    multiple_lines  internet_service_type_id online_security  \
0           Yes               Yes                         1              No
1           Yes                No                         1              No
2           Yes                No                         1             Yes
3            No  No phone service                         1              No
4            No  No phone service                         1             Yes

             ...             streaming_movies contract_type_id  \
0            ...                          Yes                1
1            ...                          Yes                1
2            ...                           No                1
3            ...                           No                1
4            ...                           No                1

  paperless_billing payment_type_id monthly_charges  total_charges churn  \
0                No               2            59.9          542.4    No
1               Yes               4            69.4         571.45    No
2               Yes               1            48.2         340.35    No
3               Yes               1            25.1           25.1   Yes
4                No               3            30.5           30.5   Yes

    contract_type  internet_service_type               payment_type
0  Month-to-month                    DSL               Mailed check
1  Month-to-month                    DSL    Credit card (automatic)
2  Month-to-month                    DSL           Electronic check
3  Month-to-month                    DSL           Electronic check
4  Month-to-month                    DSL  Bank transfer (automatic)

[5 rows x 24 columns]
     customer_id  gender  senior_citizen partner dependents  tenure  \
7038  9950-MTGYX    Male               0     Yes        Yes      28
7039  9953-ZMKSM    Male               0      No         No      63
7040  9964-WBQDJ  Female               0     Yes         No      71
7041  9972-EWRJS  Female               0     Yes        Yes      67
7042  9975-GPKZU    Male               0     Yes        Yes      46

     phone_service multiple_lines  internet_service_type_id  \
7038           Yes             No                         3
7039           Yes            Yes                         3
7040           Yes            Yes                         3
7041           Yes             No                         3
7042           Yes             No                         3

          online_security            ...                 streaming_movies  \
7038  No internet service            ...              No internet service
7039  No internet service            ...              No internet service
7040  No internet service            ...              No internet service
7041  No internet service            ...              No internet service
7042  No internet service            ...              No internet service

     contract_type_id paperless_billing payment_type_id monthly_charges  \
7038                3               Yes               4           20.30
7039                3                No               2           25.25
7040                3               Yes               4           24.40
7041                3               Yes               3           19.25
7042                3                No               4           19.75

      total_charges churn  contract_type  internet_service_type  \
7038         487.95    No       Two year                   None
7039         1559.3    No       Two year                   None
7040         1725.4    No       Two year                   None
7041         1372.9    No       Two year                   None
7042          856.5    No       Two year                   None

                   payment_type
7038    Credit card (automatic)
7039               Mailed check
7040    Credit card (automatic)
7041  Bank transfer (automatic)
7042    Credit card (automatic)

[5 rows x 24 columns]
(7043, 24)
<bound method NDFrame.describe of      customer_id  gender  senior_citizen partner dependents  tenure  \
0     0003-MKNFE    Male               0      No         No       9
1     0013-MHZWF  Female               0      No        Yes       9
2     0015-UOCOJ  Female               1      No         No       7
3     0023-HGHWL    Male               1      No         No       1
4     0032-PGELS  Female               0     Yes        Yes       1
5     0067-DKWBL    Male               1      No         No       2
6     0076-LVEPS    Male               0      No        Yes      29
7     0082-LDZUE    Male               0      No         No       1
8     0096-BXERS  Female               0     Yes         No       6
9     0096-FCPUF    Male               0      No         No      30
10    0106-GHRQR    Male               0      No         No      16
11    0117-LFRMW    Male               0     Yes        Yes      37
12    0128-MKWSG  Female               0      No        Yes      26
13    0156-FVPTA    Male               0     Yes         No      22
14    0191-ZHSKZ    Male               1      No         No      30
15    0212-ISBBF  Female               0      No         No      22
16    0222-CNVPT    Male               1      No         No      52
17    0224-HJAPT    Male               0      No         No       5
18    0224-RLWWD  Female               1      No         No       2
19    0228-MAUWC    Male               0      No         No      19
20    0248-IPDFW  Female               0      No         No       1
21    0257-KXZGU  Female               0     Yes        Yes      32
22    0260-ZDLGK  Female               0      No        Yes       9
23    0274-JKUJR    Male               0     Yes        Yes       7
24    0277-BKSQP    Male               0     Yes        Yes       8
25    0282-NVSJS  Female               1     Yes        Yes      12
26    0285-INHLN    Male               0     Yes        Yes      27
27    0289-IVARM  Female               0      No         No      35
28    0292-WEGCH  Female               0     Yes        Yes      54
29    0295-QVKPB    Male               0      No         No       5
...          ...     ...             ...     ...        ...     ...
7013  9537-JALFH    Male               0     Yes        Yes      69
7014  9548-LERKT    Male               0     Yes         No      24
7015  9565-AXSMR    Male               0     Yes        Yes      52
7016  9574-BOSMD    Male               0     Yes        Yes      68
7017  9585-KKMFD    Male               0     Yes        Yes      41
7018  9588-YRFHY    Male               0      No         No      49
7019  9593-CVZKR  Female               0     Yes        Yes      56
7020  9624-EGDEQ  Female               0      No         No      37
7021  9625-RZFUK    Male               0     Yes        Yes      63
7022  9631-RXVJM    Male               0      No         No      35
7023  9646-NMHXE    Male               0     Yes         No      47
7024  9648-BCHKM  Female               0     Yes        Yes      18
7025  9650-VBUOG    Male               0     Yes        Yes      38
7026  9661-JALZV  Female               0      No         No      58
7027  9668-PUGNU    Male               0     Yes         No      71
7028  9710-NJERN  Female               0      No         No      39
7029  9717-IOAAF    Male               0      No        Yes      27
7030  9764-REAFF  Female               0     Yes         No      59
7031  9798-OPFEM  Female               0      No         No      46
7032  9800-OUIGR    Male               0     Yes        Yes      66
7033  9814-AOUDH    Male               0      No         No      53
7034  9838-BFCQT    Male               0     Yes        Yes      72
7035  9916-AYHTC    Male               0      No         No      48
7036  9938-PRCVK  Female               0     Yes        Yes      41
7037  9945-PSVIP  Female               0     Yes        Yes      25
7038  9950-MTGYX    Male               0     Yes        Yes      28
7039  9953-ZMKSM    Male               0      No         No      63
7040  9964-WBQDJ  Female               0     Yes         No      71
7041  9972-EWRJS  Female               0     Yes        Yes      67
7042  9975-GPKZU    Male               0     Yes        Yes      46

     phone_service    multiple_lines  internet_service_type_id  \
0              Yes               Yes                         1
1              Yes                No                         1
2              Yes                No                         1
3               No  No phone service                         1
4               No  No phone service                         1
5              Yes                No                         1
6               No  No phone service                         1
7              Yes                No                         1
8              Yes               Yes                         1
9              Yes               Yes                         1
10             Yes               Yes                         1
11              No  No phone service                         1
12              No  No phone service                         1
13             Yes                No                         1
14             Yes                No                         1
15              No  No phone service                         1
16              No  No phone service                         1
17             Yes               Yes                         1
18             Yes                No                         1
19             Yes               Yes                         1
20             Yes               Yes                         1
21             Yes               Yes                         1
22             Yes                No                         1
23              No  No phone service                         1
24             Yes                No                         1
25              No  No phone service                         1
26             Yes                No                         1
27             Yes                No                         1
28             Yes               Yes                         1
29             Yes                No                         1
...            ...               ...                       ...
7013           Yes                No                         3
7014           Yes                No                         3
7015           Yes                No                         3
7016           Yes               Yes                         3
7017           Yes                No                         3
7018           Yes                No                         3
7019           Yes               Yes                         3
7020           Yes                No                         3
7021           Yes                No                         3
7022           Yes                No                         3
7023           Yes                No                         3
7024           Yes               Yes                         3
7025           Yes               Yes                         3
7026           Yes               Yes                         3
7027           Yes               Yes                         3
7028           Yes                No                         3
7029           Yes               Yes                         3
7030           Yes                No                         3
7031           Yes                No                         3
7032           Yes                No                         3
7033           Yes                No                         3
7034           Yes               Yes                         3
7035           Yes                No                         3
7036           Yes                No                         3
7037           Yes                No                         3
7038           Yes                No                         3
7039           Yes               Yes                         3
7040           Yes               Yes                         3
7041           Yes                No                         3
7042           Yes                No                         3

          online_security            ...                 streaming_movies  \
0                      No            ...                              Yes
1                      No            ...                              Yes
2                     Yes            ...                               No
3                      No            ...                               No
4                     Yes            ...                               No
5                     Yes            ...                               No
6                     Yes            ...                               No
7                      No            ...                               No
8                      No            ...                               No
9                     Yes            ...                              Yes
10                     No            ...                              Yes
11                    Yes            ...                               No
12                    Yes            ...                              Yes
13                    Yes            ...                               No
14                    Yes            ...                              Yes
15                     No            ...                              Yes
16                    Yes            ...                              Yes
17                     No            ...                               No
18                     No            ...                               No
19                     No            ...                               No
20                     No            ...                               No
21                     No            ...                               No
22                     No            ...                              Yes
23                    Yes            ...                              Yes
24                     No            ...                               No
25                     No            ...                               No
26                    Yes            ...                               No
27                    Yes            ...                               No
28                     No            ...                              Yes
29                     No            ...                               No
...                   ...            ...                              ...
7013  No internet service            ...              No internet service
7014  No internet service            ...              No internet service
7015  No internet service            ...              No internet service
7016  No internet service            ...              No internet service
7017  No internet service            ...              No internet service
7018  No internet service            ...              No internet service
7019  No internet service            ...              No internet service
7020  No internet service            ...              No internet service
7021  No internet service            ...              No internet service
7022  No internet service            ...              No internet service
7023  No internet service            ...              No internet service
7024  No internet service            ...              No internet service
7025  No internet service            ...              No internet service
7026  No internet service            ...              No internet service
7027  No internet service            ...              No internet service
7028  No internet service            ...              No internet service
7029  No internet service            ...              No internet service
7030  No internet service            ...              No internet service
7031  No internet service            ...              No internet service
7032  No internet service            ...              No internet service
7033  No internet service            ...              No internet service
7034  No internet service            ...              No internet service
7035  No internet service            ...              No internet service
7036  No internet service            ...              No internet service
7037  No internet service            ...              No internet service
7038  No internet service            ...              No internet service
7039  No internet service            ...              No internet service
7040  No internet service            ...              No internet service
7041  No internet service            ...              No internet service
7042  No internet service            ...              No internet service

     contract_type_id paperless_billing payment_type_id monthly_charges  \
0                   1                No               2           59.90
1                   1               Yes               4           69.40
2                   1               Yes               1           48.20
3                   1               Yes               1           25.10
4                   1                No               3           30.50
5                   1               Yes               1           49.25
6                   1               Yes               2           45.00
7                   1               Yes               2           44.30
8                   1                No               1           50.35
9                   1               Yes               2           64.50
10                  1               Yes               3           71.40
11                  1                No               3           40.20
12                  1                No               2           45.80
13                  1               Yes               1           54.20
14                  1               Yes               1           74.75
15                  1               Yes               1           50.35
16                  1               Yes               4           48.80
17                  1                No               1           47.15
18                  1               Yes               1           44.30
19                  1                No               1           59.55
20                  1               Yes               1           50.10
21                  1                No               3           62.45
22                  1               Yes               2           72.90
23                  1                No               2           58.85
24                  1               Yes               1           54.40
25                  1               Yes               2           29.30
26                  1               Yes               4           54.75
27                  1                No               1           60.55
28                  1               Yes               1           86.20
29                  1               Yes               4           63.95
...               ...               ...             ...             ...
7013                3                No               3           19.90
7014                3                No               2           19.75
7015                3                No               2           19.20
7016                3                No               3           25.40
7017                3               Yes               2           20.00
7018                3               Yes               4           19.90
7019                3               Yes               2           24.45

### Data Prep

In [7]:
def df_value_counts(df):
    for col in df.columns:
        n = df[col].unique().shape[0]
        col_bins = min(n,10)
        print('%s:' % col)
        if df[col].dtype in ['int64','float64'] and n>10:
            print(df[col].value_counts(bins=col_bins, sort=False))
        else:
            print(df[col].value_counts())
        print('\n')

In [8]:
df_value_counts(df)

customer_id:
5673-TIYIB    1
3446-QDSZF    1
8076-FEZKJ    1
2799-TSLAG    1
1447-GIQMR    1
5146-CBVOE    1
3043-TYBNO    1
3354-OADJP    1
2160-GPFXD    1
7234-KMNRQ    1
3640-PHQXK    1
4929-BSTRX    1
2371-JQHZZ    1
5349-AZPEW    1
7636-XUHWW    1
7956-XQWGU    1
7750-EYXWZ    1
9081-WWXKP    1
6563-VRERX    1
9378-FXTIZ    1
7016-NVRIC    1
4526-RMTLL    1
7079-QRCBC    1
5875-YPQFJ    1
5066-GFJMM    1
0125-LZQXK    1
9750-BOOHV    1
1642-HMARX    1
8040-MNRTF    1
9885-MFVSU    1
             ..
7547-EKNFS    1
2775-SEFEE    1
4366-CTOUZ    1
9101-BWFSS    1
5405-ZMYXQ    1
2305-MRGLV    1
0587-DMGBH    1
8008-OTEZX    1
7674-YTAFD    1
8395-ETZKQ    1
3571-RFHAR    1
4538-WNTMJ    1
5656-JAMLX    1
3404-JNXAX    1
5144-TVGLP    1
5816-QVHRX    1
3967-VQOGC    1
0334-ZFJSR    1
8707-RMEZH    1
8780-IXSTS    1
4203-QGNZA    1
9163-GHAYE    1
2188-SXWVT    1
9330-VOFSZ    1
3131-NWVFJ    1
5245-VDBUR    1
9548-LERKT    1
0967-BMLBD    1
9207-ZPANB    1
2528-HFYZX    1
Name: customer_id, Length: 7043, dtype: int64


gender:
Male      3555
Female    3488
Name: gender, dtype: int64


senior_citizen:
0    5901
1    1142
Name: senior_citizen, dtype: int64


partner:
No     3641
Yes    3402
Name: partner, dtype: int64


dependents:
No     4933
Yes    2110
Name: dependents, dtype: int64


tenure:
(-0.073, 7.2]    1612
(7.2, 14.4]       759
(14.4, 21.6]      570
(21.6, 28.8]      556
(28.8, 36.0]      545
(36.0, 43.2]      444
(43.2, 50.4]      452
(50.4, 57.6]      495
(57.6, 64.8]      501
(64.8, 72.0]     1109
Name: tenure, dtype: int64


phone_service:
Yes    6361
No      682
Name: phone_service, dtype: int64


multiple_lines:
No                  3390
Yes                 2971
No phone service     682
Name: multiple_lines, dtype: int64


internet_service_type_id:
2    3096
1    2421
3    1526
Name: internet_service_type_id, dtype: int64


online_security:
No                     3498
Yes                    2019
No internet service    1526
Name: online_security, dtype: int64


online_backup:
No                     3088
Yes                    2429
No internet service    1526
Name: online_backup, dtype: int64


device_protection:
No                     3095
Yes                    2422
No internet service    1526
Name: device_protection, dtype: int64


tech_support:
No                     3473
Yes                    2044
No internet service    1526
Name: tech_support, dtype: int64


streaming_tv:
No                     2810
Yes                    2707
No internet service    1526
Name: streaming_tv, dtype: int64


streaming_movies:
No                     2785
Yes                    2732
No internet service    1526
Name: streaming_movies, dtype: int64


contract_type_id:
1    3875
3    1695
2    1473
Name: contract_type_id, dtype: int64


paperless_billing:
Yes    4171
No     2872
Name: paperless_billing, dtype: int64


payment_type_id:
1    2365
2    1612
3    1544
4    1522
Name: payment_type_id, dtype: int64


monthly_charges:
(18.148999999999997, 28.3]    1606
(28.3, 38.35]                  191
(38.35, 48.4]                  365
(48.4, 58.45]                  640
(58.45, 68.5]                  474
(68.5, 78.55]                  893
(78.55, 88.6]                  953
(88.6, 98.65]                  873
(98.65, 108.7]                 754
(108.7, 118.75]                294
Name: monthly_charges, dtype: int64


total_charges:
20.2       11
           11
19.75       9
19.65       8
20.05       8
19.9        8
45.3        7
19.55       7
19.45       6
20.15       6
20.25       6
20.3        5
20.45       5
75.3        4
20.4        4
19.4        4
50.15       4
19.5        4
19.3        4
19.2        4
20.35       4
49.9        4
70.6        4
44.4        4
69.65       4
19.85       4
74.7        4
69.9        4
69.6        4
20.5        4
           ..
1973.75     1
1301.7      1
5317.8      1
6725.3      1
90.1        1
785.75      1
689.75      1
903.6       1
710.05      1
542.4       1
3370.2      1
2277.65     1
1363.45     1
2021.35     1
7880.25     1
2010.55     1
5333.35     1
2271.85     1
196.95      1
294.2       1
8443.7      1
89.9        1
3808        1
235.2       1
8012.75     1
2029.05     1
2320.8      1
1147.85     1
3970.4      1
754.65      1
Name: total_charges, Length: 6531, dtype: int64


churn:
No     5174
Yes    1869
Name: churn, dtype: int64


contract_type:
Month-to-month    3875
Two year          1695
One year          1473
Name: contract_type, dtype: int64


internet_service_type:
Fiber optic    3096
DSL            2421
None           1526
Name: internet_service_type, dtype: int64


payment_type:
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: payment_type, dtype: int64

In [9]:
df.isnull().sum()

customer_id                 0
gender                      0
senior_citizen              0
partner                     0
dependents                  0
tenure                      0
phone_service               0
multiple_lines              0
internet_service_type_id    0
online_security             0
online_backup               0
device_protection           0
tech_support                0
streaming_tv                0
streaming_movies            0
contract_type_id            0
paperless_billing           0
payment_type_id             0
monthly_charges             0
total_charges               0
churn                       0
contract_type               0
internet_service_type       0
payment_type                0
dtype: int64

#### Takeaways:
- From the information that was pull there are no null values in this dataframe

- Transform churn such that "yes" == 1, and "no" == 0

In [12]:
encoder = LabelEncoder()

encoder.fit(df.churn)
df.churn = encoder.transform(df.churn)

In [11]:
df.churn.value_counts(dropna=False)

0    5174
1    1869
Name: churn, dtype: int64

In [13]:
df.tenure.head()

0    9
1    9
2    7
3    1
4    1
Name: tenure, dtype: int64