# Classification Project

1. [Goals](#Goals)
1. [Questions](#Questions)
1. [Specification](#Specification)
1. [Deliverables](#Deliverables)
1. [Prepare the Environment](#Prepare-the-Environment)
1. [Acquistion](#Acquisition)
1. [Data Prep](#Data-Prep)
1. [Data Exploration](#Data-Exploration)
1. [Modeling](#Modeling)

### Goals

- Why are our customers churning?

### Questions

- Could the month in which they signed up influence churn? i.e. if a cohort is identified by tenure, is there a cohort or cohorts who have a higher rate of churn than other cohorts? (Plot the rate of churn on a line chart where x is the tenure and y is the rate of churn (customers churned/total customers))

- Are there features that indicate a higher propensity to churn? like type of 
internet service, type of phone service, online security and backup, senior citizens, paying more than x% of customers with the same services, etc.?

- Is there a price threshold for specific services where the likelihood of churn increases once price for those services goes past that point? If so, what is that point for what service(s)?

- If we looked at churn rate for month-to-month customers after the 12th month and that of 1-year contract customers after the 12th month, are those rates comparable?

### Deliverables

1. I will also need a report (ipynb) answering the question, "Why are our customers churning?" I want to see the analysis you did to answer my questions and lead to your findings. Please clearly call out the questions and answers you are analyzing. E.g. If you find that month-to-month customers churn more, I won't be surprised, but I am not getting rid of that plan. The fact that they churn is not because they can, it's because they can and they are motivated to do so. I want some insight into why they are motivated to do so. I realize you will not be able to do a full causal experiment, but I hope to see some solid evidence of your conclusions.

2. I will need you to deliver to me a csv with the customer_id, probability of churn, and the prediction of churn (1=churn, 0=not_churn). I would also like a single goolgle slide that illustrates how your model works, including the features being used, so that I can deliver this to the SLT when they come with questions about how these values were derived. Please make sure you include how likely your model is to give a high probability of churn when churn doesn't occur, to give a low probability of churn when churn occurs, and to accurately predict churn.

3. Finally, our development team will need a .py file that will take in a new dataset, (in the exact same form of the one you acquired from telco_churn.customers) and perform all the transformations necessary to run the model you have developed on this new dataset to provide probabilities and predictions.

### Specification

Detailed instructions for each section are below.

In general, make sure you document your work. You don't need to explain what every line of code is doing, but you should explain what and why you are doing. For example, if you drop a feature from the dataset, you should explain why you decided to do so, or why that is a reasonable thing to do. If you transform the data in a column, you should explain why you are making that transformation.

In addition, you should not present numers in isolation. If your code outputs a number, be sure you give some context to the number.

Specific Deliverables:

- a jupyter notebook where your work takes place
- a csv file that predicts churn for each customer
- a python script that prepares data such that it can be fed into your model
- a google slide summarizing your model
- a README.md file that contains a link to your google slides presentation, and instructions for how to use your python script(s)

### Prepare the Environment

In [7]:
# ignore warnings
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

from pydataset import data

# Logistc Regression
from sklearn.linear_model import LogisticRegression

# Decision Tree
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree

# KNN
from sklearn.neighbors import KNeighborsClassifier

# Random Forest
from sklearn.ensemble import RandomForestClassifier

# All modeling
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

from sklearn.preprocessing import MinMaxScaler

import graphviz

from graphviz import Graph

import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

from env import host, user, password

### Acquisition

1. Get the data from the ```customers``` table from the ```telco_churn``` database on the codeup data science database server.

    - You may wish to join some tables as part of your query.
    - This data should end up in a pandas data frame.

In [8]:
def get_db_url(hostname: str, username: str, password: str, db_name: str) -> str:
    return f"mysql+pymysql://{username}:{password}@{hostname}/{db_name}"


def get_sql_conn(hostname: str, username: str, password: str, db_name: str):
    return create_engine(get_db_url(host, user, password, db_name))


def df_from_sql(query: str, url: str) -> pd.DataFrame:
    return pd.read_sql(query, url)


def get_telco_data() -> pd.DataFrame:
    db = "telco_churn"
    query = ("SELECT * "
             f"FROM customers;")
    url = get_db_url(host, user, password, db)
    return df_from_sql(query, url)

In [9]:
df = get_telco_data()

In [10]:
df.head()

,customer_id,gender,senior_citizen,partner,dependents,tenure,phone_service,multiple_lines,internet_service_type_id,online_security,...,device_protection,tech_support,streaming_tv,streaming_movies,contract_type_id,paperless_billing,payment_type_id,monthly_charges,total_charges,churn
0,0002-ORFBO,Female,0,Yes,Yes,9,Yes,No,1,No,...,No,Yes,Yes,No,2,Yes,2,65.6,593.3,No
1,0003-MKNFE,Male,0,No,No,9,Yes,Yes,1,No,...,No,No,No,Yes,1,No,2,59.9,542.4,No
2,0004-TLHLJ,Male,0,No,No,4,Yes,No,2,No,...,Yes,No,No,No,1,Yes,1,73.9,280.85,Yes
3,0011-IGKFF,Male,1,Yes,No,13,Yes,No,2,No,...,Yes,No,Yes,Yes,1,Yes,1,98.0,1237.85,Yes
4,0013-EXCHZ,Female,1,Yes,No,3,Yes,No,2,No,...,No,Yes,Yes,No,1,Yes,2,83.9,267.4,Yes

2. Write a function, ```peekatdata(dataframe)```, that takes a dataframe as input and computes and returns the following:

    - creates dataframe object ```head_df``` (df of the first 5 rows) and prints contents to screen

    - creates dataframe object ```tail_df``` (df of the last 5 rows) and prints contents to screen

    - creates tuple object ```shape_tuple``` (tuple of (nrows, ncols)) and prints tuple to screen

    - creates dataframe object ```describe_df``` (summary statistics of all numeric variables) and prints contents to screen.

    - prints to screen the information about a DataFrame including the index dtype and column dtypes, non-null values and memory usage.

In [11]:
def peekatdata(dataframe):
    head_df = dataframe.head()
    print(f"HEAD\n{head_df}", end="\n\n")

    tail_df = dataframe.tail()
    print(f"TAIL\n{tail_df}", end="\n\n")

    shape_tuple = dataframe.shape
    print(f"SHAPE: {shape_tuple}", end="\n\n")

    describe_df = dataframe.describe()
    print(f"DESCRIPTION\n{describe_df}", end="\n\n")

    print(f"INFORMATION")
    dataframe.info()

In [12]:
peekatdata(df)

HEAD
  customer_id  gender  senior_citizen partner dependents  tenure  \
0  0002-ORFBO  Female               0     Yes        Yes       9
1  0003-MKNFE    Male               0      No         No       9
2  0004-TLHLJ    Male               0      No         No       4
3  0011-IGKFF    Male               1     Yes         No      13
4  0013-EXCHZ  Female               1     Yes         No       3

  phone_service multiple_lines  internet_service_type_id online_security  ...  \
0           Yes             No                         1              No  ...
1           Yes            Yes                         1              No  ...
2           Yes             No                         2              No  ...
3           Yes             No                         2              No  ...
4           Yes             No                         2              No  ...

  device_protection tech_support streaming_tv streaming_movies  \
0                No          Yes          Yes               No
1                No           No           No              Yes
2               Yes           No           No               No
3               Yes           No          Yes              Yes
4                No          Yes          Yes               No

  contract_type_id  paperless_billing payment_type_id  monthly_charges  \
0                2                Yes               2             65.6
1                1                 No               2             59.9
2                1                Yes               1             73.9
3                1                Yes               1             98.0
4                1                Yes               2             83.9

   total_charges churn
0          593.3    No
1          542.4    No
2         280.85   Yes
3        1237.85   Yes
4          267.4   Yes

[5 rows x 21 columns]

TAIL
     customer_id  gender  senior_citizen partner dependents  tenure  \
7038  9987-LUTYD  Female               0      No         No      13
7039  9992-RRAMN    Male               0     Yes         No      22
7040  9992-UJOEL    Male               0      No         No       2
7041  9993-LHIEB    Male               0     Yes        Yes      67
7042  9995-HOTOH    Male               0     Yes        Yes      63

     phone_service    multiple_lines  internet_service_type_id  \
7038           Yes                No                         1
7039           Yes               Yes                         2
7040           Yes                No                         1
7041           Yes                No                         1
7042            No  No phone service                         1

     online_security  ... device_protection tech_support streaming_tv  \
7038             Yes  ...                No          Yes           No
7039              No  ...                No           No           No
7040              No  ...                No           No           No
7041             Yes  ...               Yes          Yes           No
7042             Yes  ...               Yes           No          Yes

     streaming_movies contract_type_id  paperless_billing payment_type_id  \
7038               No                2                 No               2
7039              Yes                1                Yes               1
7040               No                1                Yes               2
7041              Yes                3                 No               2
7042              Yes                3                 No               1

      monthly_charges  total_charges churn
7038            55.15          742.9    No
7039            85.10         1873.7   Yes
7040            50.30          92.75    No
7041            67.85        4627.65    No
7042            59.00         3707.6    No

[5 rows x 21 columns]

SHAPE: (7043, 21)

DESCRIPTION
       senior_citizen       tenure  internet_service_type_id  \
count     7043.000000  7043.000000               7043.000000
mean         0.162147    32.371149                  1.872923
std          0.368612    24.559481                  0.737796
min          0.000000     0.000000                  1.000000
25%          0.000000     9.000000                  1.000000
50%          0.000000    29.000000                  2.000000
75%          0.000000    55.000000                  2.000000
max          1.000000    72.000000                  3.000000

       contract_type_id  payment_type_id  monthly_charges
count       7043.000000      7043.000000      7043.000000
mean           1.690473         2.315633        64.761692
std            0.833755         1.148907        30.090047
min            1.000000         1.000000        18.250000
25%            1.000000         1.000000        35.500000
50%            1.000000         2.000000        70.350000
75%            2.000000         3.000000        89.850000
max            3.000000         4.000000       118.750000

INFORMATION
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
customer_id                 7043 non-null object
gender                      7043 non-null object
senior_citizen              7043 non-null int64
partner                     7043 non-null object
dependents                  7043 non-null object
tenure                      7043 non-null int64
phone_service               7043 non-null object
multiple_lines              7043 non-null object
internet_service_type_id    7043 non-null int64
online_security             7043 non-null object
online_backup               7043 non-null object
device_protection           7043 non-null object
tech_support                7043 non-null object
streaming_tv                7043 non-null object
streaming_movies            7043 non-null object
contract_type_id            7043 non-null int64
paperless_billing           7043 non-null object
payment_type_id             7043 non-null int64
monthly_charges             7043 non-null float64
total_charges               7043 non-null object
churn                       7043 non-null object
dtypes: float64(1), int64(5), object(15)
memory usage: 1.1+ MB

### Data Prep

1. Write a function, ```df_value_counts(dataframe)```, that takes a dataframe as input and computes and returns the values by frequency for each column. The function should decide whether or not to bin the data for the value counts.

In [13]:
def df_value_counts(dataframe):
    for col in df.columns:
        n = df[col].unique().shape[0]
        col_bins = min(n, 10)
        print(f"{col}:")
        if df[col].dtype in ['int64', 'float64'] and n > 10:
            print(df[col].value_counts(bins=col_bins, sort=False))
        else:
            print(df[col].value_counts())
        print("\n")

In [14]:
df_value_counts(df)

customer_id:
3751-KTZEL    1
1391-UBDAR    1
0620-XEFWH    1
6982-UQZLY    1
8450-LUGUK    1
9470-YFUYI    1
9688-YGXVR    1
0979-PHULV    1
2592-SEIFQ    1
9638-JIQYA    1
7021-XSNYE    1
6656-GULJQ    1
2607-FBDFF    1
3071-MVJCD    1
6591-QGOYB    1
7163-OCEQI    1
4500-HKANN    1
7176-WRTNX    1
5133-POWUA    1
4830-FAXFM    1
9518-XXBXE    1
1842-EZJMK    1
6421-SZVEM    1
7208-PSIHR    1
5740-YHGTW    1
3757-NJYBX    1
8224-KDLKN    1
6048-NJXHX    1
9677-AVKED    1
4010-YLMVT    1
2234-EOFPT    1
0224-HJAPT    1
8800-JOOCF    1
6330-JKLPC    1
7459-RRWQZ    1
4488-PSYCG    1
5622-UEJFI    1
5989-AXPUC    1
5751-USDBL    1
3518-FSTWG    1
3932-IJWDZ    1
7688-AWMDX    1
6177-PEVRA    1
1522-VVDMG    1
8430-TWCBX    1
3158-MOERK    1
2710-WYVXG    1
3500-NSDOA    1
5781-BKHOP    1
2612-PHGOX    1
7225-CBZPL    1
7609-YBPXG    1
9800-OUIGR    1
1837-YQUCE    1
8008-ESFLK    1
0187-QSXOE    1
8270-RKSAP    1
0680-DFNNY    1
0181-RITDD    1
5915-ANOEI    1
7277-OZCGZ    1
7492-TAFJD    1
8988-ECPJR    1
1563-IWQEX    1
1216-BGTSP    1
4782-OSFXZ    1
7544-ZVIKX    1
2636-ALXXZ    1
8720-RQSBJ    1
9867-XOBQA    1
7654-YWJUF    1
2718-GAXQD    1
8010-EZLOU    1
4597-ELFTS    1
3748-FVMZZ    1
9874-QLCLH    1
5816-SCGFC    1
8008-HAWED    1
6013-BHCAW    1
8413-VONUO    1
0771-WLCLA    1
9030-QGZNL    1
8966-OIQHG    1
7130-VTEWQ    1
3639-XJHKQ    1
             ..
1704-NRWYE    1
0516-QREYC    1
5003-OKNNK    1
8718-PTMEZ    1
5375-XLDOF    1
3679-XASPY    1
4187-CINZD    1
1343-EHPYB    1
9108-EJFJP    1
3030-ZKIWL    1
1921-KYSAY    1
1113-IUJYX    1
3812-LRZIR    1
1448-CYWKC    1
8571-ZCMCX    1
0440-UEDAI    1
2853-CWQFQ    1
4062-HBMOS    1
4694-PHWFW    1
6513-EECDB    1
6437-UKHMV    1
2072-ZVJJX    1
3217-FZDMN    1
9361-YNQWJ    1
9692-TUSXH    1
4950-HKQTE    1
9229-RQABD    1
2866-IKBTM    1
3221-CJMSG    1
2405-LBMUW    1
4644-PIZRT    1
5249-QYHEX    1
6169-PGNCD    1
0089-IIQKO    1
4860-IJUDE    1
5619-PTMIK    1
6188-UXBBR    1
1354-YZFNB    1
2262-SLNVK    1
7901-HXJVA    1
0818-OCPZO    1
9134-CEQMF    1
8294-UIMBA    1
9553-DLCLU    1
5973-EJGDP    1
5044-LRQAQ    1
4662-EKDPQ    1
0979-MOZQI    1
4360-PNRQB    1
8902-ZEOVF    1
6133-OZILE    1
4698-KVLLG    1
9600-UDOPK    1
1866-ZSLJM    1
6235-VDHOM    1
4468-YDOVK    1
0407-BDJKB    1
7952-OBOYL    1
5879-SESNB    1
9530-GRMJG    1
4903-CNOZC    1
0784-ZQJZX    1
7718-RXDGG    1
4719-UMSIY    1
4883-QICIH    1
2880-FPNAE    1
3669-OYSJI    1
3739-YBWAB    1
3736-BLEPA    1
9916-AYHTC    1
4315-MURBD    1
6169-PPETC    1
4220-TINQT    1
6999-CHVCF    1
5480-HPRRX    1
7596-IIWYC    1
1768-ZAIFU    1
4840-ORQXB    1
8944-AILEF    1
1009-IRMNA    1
5847-MXBEO    1
8565-HBFNN    1
7691-KGKGP    1
2017-CCBLH    1
5568-DMXZS    1
Name: customer_id, Length: 7043, dtype: int64


gender:
Male      3555
Female    3488
Name: gender, dtype: int64


senior_citizen:
0    5901
1    1142
Name: senior_citizen, dtype: int64


partner:
No     3641
Yes    3402
Name: partner, dtype: int64


dependents:
No     4933
Yes    2110
Name: dependents, dtype: int64


tenure:
(-0.073, 7.2]    1612
(7.2, 14.4]       759
(14.4, 21.6]      570
(21.6, 28.8]      556
(28.8, 36.0]      545
(36.0, 43.2]      444
(43.2, 50.4]      452
(50.4, 57.6]      495
(57.6, 64.8]      501
(64.8, 72.0]     1109
Name: tenure, dtype: int64


phone_service:
Yes    6361
No      682
Name: phone_service, dtype: int64


multiple_lines:
No                  3390
Yes                 2971
No phone service     682
Name: multiple_lines, dtype: int64


internet_service_type_id:
2    3096
1    2421
3    1526
Name: internet_service_type_id, dtype: int64


online_security:
No                     3498
Yes                    2019
No internet service    1526
Name: online_security, dtype: int64


online_backup:
No                     3088
Yes                    2429
No internet service    1526
Name: online_backup, dtype: int64


device_protection:
No                     3095
Yes                    2422
No internet service    1526
Name: device_protection, dtype: int64


tech_support:
No                     3473
Yes                    2044
No internet service    1526
Name: tech_support, dtype: int64


streaming_tv:
No                     2810
Yes                    2707
No internet service    1526
Name: streaming_tv, dtype: int64


streaming_movies:
No                     2785
Yes                    2732
No internet service    1526
Name: streaming_movies, dtype: int64


contract_type_id:
1    3875
3    1695
2    1473
Name: contract_type_id, dtype: int64


paperless_billing:
Yes    4171
No     2872
Name: paperless_billing, dtype: int64


payment_type_id:
1    2365
2    1612
3    1544
4    1522
Name: payment_type_id, dtype: int64


monthly_charges:
(18.148999999999997, 28.3]    1606
(28.3, 38.35]                  191
(38.35, 48.4]                  365
(48.4, 58.45]                  640
(58.45, 68.5]                  474
(68.5, 78.55]                  893
(78.55, 88.6]                  953
(88.6, 98.65]                  873
(98.65, 108.7]                 754
(108.7, 118.75]                294
Name: monthly_charges, dtype: int64


total_charges:
           11
20.2       11
19.75       9
19.65       8
20.05       8
19.9        8
19.55       7
45.3        7
20.15       6
20.25       6
19.45       6
20.45       5
20.3        5
69.6        4
19.3        4
75.3        4
69.95       4
44          4
19.85       4
74.7        4
69.9        4
50.15       4
70.6        4
20.35       4
19.4        4
44.4        4
69.65       4
19.95       4
19.2        4
19.5        4
49.9        4
20.5        4
20.4        4
20          3
25.25       3
45.7        3
24.8        3
86.05       3
50.6        3
85          3
1284.2      3
24.4        3
74.9        3
220.45      3
20.1        3
70.3        3
19.1        3
85.5        3
84.5        3
75.35       3
55.7        3
50.45       3
80.55       3
74.3        3
305.55      3
69.25       3
35.9        3
70.15       3
20.9        3
50.75       3
20.55       3
74.35       3
70.45       3
45.1        3
470.2       3
69.1        3
45.85       3
74.6        3
79.55       3
19.25       3
44.75       3
69.55       3
383.65      3
2317.1      3
70.1        3
70          2
1410.25     2
90.05       2
83.75       2
181.65      2
53.55       2
25.1        2
1174.35     2
1672.1      2
90.6        2
           ..
1039.45     1
786.3       1
1583.5      1
8477.7      1
760.05      1
5890        1
25.8        1
1101.85     1
1311.3      1
4443.45     1
609.05      1
452.35      1
168.2       1
1336.1      1
1166.7      1
390.4       1
7099        1
5377.8      1
1756.2      1
4135        1
319.6       1
2515.3      1
504.2       1
7069.25     1
3162.65     1
266.6       1
1203.95     1
2405.05     1
467.85      1
4916.4      1
1654.45     1
146.3       1
100.4       1
2779.5      1
6822.15     1
1959.5      1
179.35      1
3042.25     1
2995.45     1
60.15       1
241.3       1
890.35      1
5897.4      1
220.95      1
4374.55     1
3343.15     1
4213.9      1
5914.4      1
1513.6      1
1147.85     1
86.35       1
1500.5      1
406.95      1
5638.3      1
1183.2      1
590.35      1
799         1
4242.35     1
157.65      1
3778        1
1451.1      1
168.65      1
8425.3      1
6263.8      1
492         1
411.25      1
321.9       1
368.85      1
2198.3      1
4566.5      1
7665.8      1
206.6       1
1421.75     1
1948.35     1
1346.2      1
89.15       1
4392.5      1
1992.85     1
6615.15     1
921.3       1
5376.4      1
736.8       1
1374.35     1
6858.9      1
2839.65     1
Name: total_charges, Length: 6531, dtype: int64


churn:
No     5174
Yes    1869
Name: churn, dtype: int64

2. Handle Missing Values

    - Explore the data and see if there are any missing values.

    Write a function that accepts a dataframe and returns the names of the columns that have missing values, and the percent of missing values in each column that has missing values.

    - Document your takeaways. For each variable:

        - should you remove the observations with a missing value for that variable?
        - should you remove the variable altogether?
        - is missing equivalent to 0 (or some other constant value) in the specific case of this variable?
        - should you replace the missing values with a value it is most likely to represent (e.g. Are the missing values a result of data integrity issues and should be replaced by the most likely value?)
        
    - Handle the missing values in the way you recommended above.

3. Transform ```churn``` such that "yes" = 1 and "no" = 0

4. Compute a new feature, ```tenure_year``` , that is a result of translating tenure from months to years.

5. Figure out a way to capture the information contained in ```phone_service``` and ```multiple_lines``` into a single variable of dtype int. Write a function that will transform the data and place in a new column named ```phone_id```.

6. Figure out a way to capture the information contained in ```dependents``` and ```partner``` into a single variable of dtype int. Transform the data and place in a new column ```household_type_id```.

7. Figure out a way to capture the information contained in streaming_tv and streaming_movies into a single variable of dtype int. Transform the data and place in a new column streaming_services.

8. Figure out a way to capture the information contained in online_security and online_backup into a single variable of dtype int. Transform the data and place in a new column online_security_backup.

9. Split the data into train (70%) & test (30%) samples.

10. Variable Encoding: encode the values in each non-numeric feature such that they are numeric.

11. Numeric Scaling: scale the monthly_charges and total_charges data. Make sure that the parameters for scaling are learned from the training data set.

### Data Exploration

1. Could the month in which they signed up influence churn? i.e. if a cohort is identified by tenure, is there a cohort or cohorts who have a higher rate of churn than other cohorts? (Plot the rate of churn on a line chart where x is the tenure and y is the rate of churn (customers churned/total customers)).

2. Are there features that indicate a higher propensity to churn? like type of internet service, type of phone service, online security and backup, senior citizens, paying more than x% of customers with the same services, etc.?

3. Is there a price threshold for specific services where the likelihood of churn increases once price for those services goes past that point? If so, what is that point for what service(s)?

4. If we looked at churn rate for month-to-month customers after the 12th month and that of 1-year contract customers after the 12th month, are those rates comparable?

5. Controlling for services (phone_id, internet_service_type_id, online_security_backup, device_protection, tech_support, and contract_type_id), is the mean monthly_charges of those who have churned significantly different from that of those who have not churned? (Use a t-test to answer this.)

6. How much of ```monthly_charges``` can be explained by ```internet_service_type```? (hint: correlation test). State your hypotheses and your conclusion clearly.

7. How much of ```monthly_charges``` can be explained by ```internet_service_type``` + phone service type (0, 1, or multiple lines). State your hypotheses and your conclusion clearly.

8. Create visualizations exploring the interactions of variables (independent with independent and independent with dependent). The goal is to identify features that are related to churn, identify any data integrity issues, understand 'how the data works'. For example, we may find that all who have online services also have device protection. In that case, we don't need both of those. (The visualizations done in your analysis for questions 1-5 count towards the requirements below)

    - Each independent variable (except for customer_id) should be visualized in at least two plots, and at least 1 of those compares the independent variable with the dependent variable.

    - For each plot where x and y are independent variables, add a third dimension (where possible), of churn represented by color.

    - Use subplots when plotting the same type of chart but with different variables.

    - Adjust the axes as necessary to extract information from the visualizations (adjusting the x & y limits, setting the scale where needed, etc.)

    - Add annotations to at least 5 plots with a key takeaway from that plot.

    - Use plots from matplotlib, pandas and seaborn.

    - Use each of the following:

        - sns.heatmap
        - pd.crosstab (along with sns.heatmap)
        - pd.scatter_matrix
        - sns.barplot
        - sns.swarmplot
        - sns.pairplot
        - sns.jointplot
        - sns.relplot or plt.scatter
        - sns.distplot or plt.hist
        - sns.boxplot
        - plt.plot

    - Use at least one more type of plot that is not included in the list above.

9. What can you say about each variable's relationship to churn, based on your initial exploration? If there appears to be some sort of interaction or correlation, assume there is no causal relationship and brainstorm (and document) ideas on reasons there could be correlation.

10. Summarize your conclusions, provide clear answers to the specific questions, and summarize any takeaways/action plan from the work above.

### Modeling

1. Feature Selection: Are there any variables that seem to provide limited to no additional information? If so, remove them.

2. Train (fit, transform, evaluate) multiple different models, varying the model type and your meta-parameters.

3. Compare evaluation metrics across all the models, and select the best performing model.

4. Test the final model (transform, evaluate) on your out-of-sample data (the testing data set). Summarize the performance. Interpret your results.